/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.kantinbusri;

/**
 *
 * @author AlfiansyahAchmad
 */
public class ItemPanel extends javax.swing.JPanel {
    public String namaMakanan;
    public int qty = 0;
    public int hargaAsli;

    public int getHargaTotal() {
        return hargaAsli * qty;
    }

    public ItemPanel(String namaMakanan, int hargaAsli) {
        this.namaMakanan = namaMakanan;
        this.hargaAsli = hargaAsli;

        initComponents();
        
        labelNamaMakanan.setText(this.namaMakanan);
        refresh();
        
    }
    
    public final void refresh() {
        labelQty.setText(String.valueOf(qty));
        labelHargaTotal.setText(Utils.formatHarga(getHargaTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRasa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelQty = new javax.swing.JLabel();
        labelNamaMakanan = new javax.swing.JLabel();
        buttonTambahQty = new javax.swing.JButton();
        buttonKurangQty = new javax.swing.JButton();
        labelHargaTotal = new javax.swing.JLabel();
        rasaBiasa = new javax.swing.JRadioButton();
        rasaPedas = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));

        labelQty.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelQty.setText("0");

        labelNamaMakanan.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelNamaMakanan.setText("NAMA MAKANAN");

        buttonTambahQty.setText("+");
        buttonTambahQty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTambahQtyMouseClicked(evt);
            }
        });

        buttonKurangQty.setText("-");
        buttonKurangQty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonKurangQtyMouseClicked(evt);
            }
        });

        labelHargaTotal.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelHargaTotal.setText("Rp0");

        groupRasa.add(rasaBiasa);
        rasaBiasa.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        rasaBiasa.setSelected(true);
        rasaBiasa.setText("Biasa");

        groupRasa.add(rasaPedas);
        rasaPedas.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        rasaPedas.setText("Pedas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rasaBiasa)
                        .addGap(18, 18, 18)
                        .addComponent(rasaPedas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNamaMakanan)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(labelHargaTotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonKurangQty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelQty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTambahQty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaMakanan)
                    .addComponent(labelHargaTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQty)
                    .addComponent(buttonTambahQty)
                    .addComponent(buttonKurangQty)
                    .addComponent(rasaPedas)
                    .addComponent(rasaBiasa))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void buttonTambahQtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTambahQtyMouseClicked
        // TODO add your handling code here:
        handleButtonClick("tambah");
    }//GEN-LAST:event_buttonTambahQtyMouseClicked

    private void buttonKurangQtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKurangQtyMouseClicked
        // TODO add your handling code here:
        handleButtonClick("kurang");
    }//GEN-LAST:event_buttonKurangQtyMouseClicked
    
    public void handleButtonClick(String tipe) {
        if (tipe.equalsIgnoreCase("kurang") && qty > 1) {
            qty--;
        } else if (tipe.equalsIgnoreCase("tambah")) {
            qty++;
        }
        
        refresh();
        this.firePropertyChange("qtyChange", 0, 1);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKurangQty;
    private javax.swing.JButton buttonTambahQty;
    private javax.swing.ButtonGroup groupRasa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHargaTotal;
    private javax.swing.JLabel labelNamaMakanan;
    private javax.swing.JLabel labelQty;
    private javax.swing.JRadioButton rasaBiasa;
    private javax.swing.JRadioButton rasaPedas;
    // End of variables declaration//GEN-END:variables
}
